### ISSUE TITLE
Limitação no tamanho do nome de coluna

### ISSUE THREAD

**Issue by victorpedrocs** [MDArte/mdarte#20]
Ao criar um atributo em uma classe com o nome **flexibilizar_campos_controlados** (31 caracteres) percebi que o nome da coluna na tabela referente ao modelo que estava alterando ficou com o nome **flexibilizar_campos_controlado** (30 caracteres).

Depois percebi que qualquer nome maior que 30 caracteres era limitado, porém, apenas no banco.

No código java ele fica da mesma forma como é escrito no modelo.

**Comment by sio-iago** [comment]
http://stackoverflow.com/questions/8213127/maximum-characters-in-labels-table-names-columns-etc
