### ISSUE TITLE
Posição errada de elementos ao diminuir o tamanho da janela.

### ISSUE THREAD

**Issue by glaucoot** [MDArte/mdarte#8]
Ao diminuir o tamanho da tela, os labels estão ficando a direita dos campos para preencher. O correto seria os labels permanecerem a esquerda.

**Comment by fmilepe** [comment]
Classe 'row' removida de todas as divs que englobam campos, classe
'form-horizontal' adicionada aos formulários. 

Div adicionada dentro da div que engloba o checkbox, fincando
div>div>label>checkbox. A div adicionada recebeu o conjunto de classes
"col-sm-offset-1 col-sm-10" e a label que contém o checkbox perdeu suas
classes.
