### ISSUE TITLE
Controle de Acesso

### ISSUE THREAD

**Issue by marcelols83** [MDArte/mdarte#9]
Felipe, estou trabalhando aqui na Marinha com o MDA. Nosso cartucho é o 16. Precisamos implementar bloqueio de login simultâneo para mesmo usuário. Queria entender mais como funcionar o controle de acesso e se tem a possibilidade de implementar isso usando as tabelas atuais e/ou a sessão criada por ele.

Estamos usando o security-1.1.2.jar

**Comment by filipebraida** [comment]
Marcelo,

recomendo criar um objeto onde ficará os logins dos usuários logados e no ControleAcessoImpl poderia guardar o último login quando o usuário tiver acesso. Se tentar se logar e o tempo mínimo não tiver passado pode bloquear.

Pode também fazer com ajax em todas as telas falando um ping para o servidor informando que aquele usuário está logado.

Abraço

**Comment by filipebraida** [comment]
O Login.java é o lugar onde é feito o login. Vocês podem mudar essa classe para atender as suas necessidades.
